### ISSUE TITLE
ModuleNotFoundError: No module named 'ttkthemes'

### ISSUE THREAD

**Issue by TemirlanMyrzakhmet** [TkinterEP/ttkthemes#71]
I have installed the ttkthemes by using the following method:
python3 -m pip install git+https://github.com/RedFantom/ttkthemes

I have following versions of pillow and pillow and ttkthemes:
Successfully installed pillow-7.1.2 ttkthemes-3.0.0

However, when I was trying to run the example program you included I have received the error displayed below:
error-from ttkthemes import ThemedTk
ModuleNotFoundError: No module named 'ttkthemes'

Is there a way of resolving this issue?

**Comment by RedFantom** [comment]
That actually doesn't sound like it has anything to do with the library itself... In order to help you, and this certainly does sound like a more general Python issue, I will need some more information.

Are you on Windows or on Linux? Are you using PyCharm or some other IDE, or are you using plain IDLE? Are you using a `virtualenv`, a system-wide installation (to `C:\Program Files\Python*` or `C:\Python*` on Windows) or a local installation `to `~\AppData` or whatever it hangs out in these days on Windows)? The latter is the default way it gets installed on Windows.

You can always just try searching for the `ttkthemes` directory on your full PC. It should pop up, and it's parent folder should be present in the output of the following script:
```
import site
print(site.getsitepackages())
```

**Comment by TemirlanMyrzakhmet** [comment]
It is was a general Python problem indeed. I was able to successfully run the program. It appeared that I just had to move the ttkthemes folder to the directory where my .py program was located. Now everything works fine.

Thank you very much!

**Comment by RedFantom** [comment]
Okay, glad to hear it. Have fun with the themes!

**Comment by Akuli** [comment]
You shouldn't need to move everything into the same folder with your program. Maybe you were using a virtualenv when running the program but not when installing ttkthemes?
